name: Product Catalog Service
owner: Data Platform Team
status: Active
access:
  - Internal
update_frequency: hourly
sensitivity: Internal
sla: "99.9% availability; ≤60 min freshness during business hours"

description: Central source of truth for product data (names, categories, pricing, availability).
tags: [product, catalog, api, curated]

business_purpose: Enable consistent product information across apps and analytics.
kpis:
  - "Price completeness ≥ 99%"
  - "SKU coverage ≥ 99.5%"

quality:
  freshness_sla_min: 60
  completeness_target_pct: 99.0

sources:
  - mdm.products
  - pricing.rules

monitoring:
  - "Dashboard: Grafana › Product Catalog"
  - "Alert: Freshness > 60m"

support: "data-platform@example.org"
schema_uri: https://example.org/schemas/product-catalog.json
