name: Build & publish catalog.json for Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Validate & build (build/catalog.json)
        run: |
          chmod +x tools/validate.sh || true
          tools/validate.sh

      - name: Copy build → docs
        run: |
          mkdir -p docs
          cp -f build/catalog.json docs/catalog.json

      - name: Open PR with updated catalog.json
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update docs/catalog.json from services/*"
          branch: auto/catalog-update
          title: "chore: publish updated catalog.json"
          body: |
            Auto-generated PR updating **docs/catalog.json** from files in `services/`.
            Merging this PR updates the published site.
          add-paths: |
            docs/catalog.json
