name: Build & publish catalog.json for Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          RUAMEL_NO_EXTENSIONS: "1"

      - name: Generate build/catalog.json
        run: bash tools/validate.sh

      - name: Copy catalog for GitHub Pages
        run: |
          mkdir -p docs
          cp build/catalog.json docs/catalog.json

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update catalog.json (CI)"
          file_pattern: docs/catalog.json
