name: Build & publish catalog.json for Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Validate & build (build/catalog.json)
        run: |
          chmod +x tools/validate.sh || true
          tools/validate.sh

      - name: Copy build → docs
        run: |
          mkdir -p docs
          cp -f build/catalog.json docs/catalog.json

      - name: Commit docs/catalog.json if changed
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Only stage what the site uses
          git add -A docs/catalog.json

          # Helpful debug
          git status --porcelain
          git diff --stat --cached || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update docs/catalog.json from services/*"
            git push origin HEAD:main
          fi
